# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: Default

stages:
- stage: Build
  displayName: Push to S3 Bucket
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: AWSCLI@1
      displayName: Sync with AWS Bucket
      inputs:
        awsCredentials: 'AWS Codexponent'
        regionName: 'us-east-1'
        awsCommand: 's3'
        awsSubCommand: 'sync'
        awsArguments: '. $(bucket-name)'

    - task: AWSCLI@1
      displayName: Sync with AWS Bucket
      inputs:
        awsCredentials: 'AWS Codexponent'
        regionName: 'us-east-1'
        awsCommand: 's3'
        awsSubCommand: 'sync'
        awsArguments: 'resume/ $(resume-bucket-name)'

    - task: FtpUpload@2
      inputs:
        credentialsOption: 'serviceEndpoint'
        serverEndpoint: 'FTP Service Connection 1'
        rootDirectory: '.'
        filePatterns: '**'
        remoteDirectory: '/public_html/'
        clean: true
        preservePaths: false
        trustSSL: false